export const dataNotifications = [
	{
		username: "Mark Webber",
		paragraph: "reacted to your recent post ",
		link: "My first tournament today!",
		timestamp: "1m ago",
		message: "",
		avatar: "../../public/assets/images/avatar-mark-webber.webp",
		picture: "",
		isread: "no",
	},
	{
		username: "Angela Gray",
		paragraph: "followed you",
		link: "",
		timestamp: "5m ago",
		message: "",
		avatar: "../../public/assets/images/avatar-angela-gray.webp",
		picture: "",
		isread: "no",
	},
	{
		username: "Jacob Thompson",
		paragraph: "has joined your group ",
		link: "Chess Club",
		timestamp: "1 day ago",
		message: "",
		avatar: "../../public/assets/images/avatar-jacob-thompson.webp",
		picture: "",
		isread: "no",
	},
	{
		username: "Rizky hasanuddin",
		paragraph: "sent you a private message",
		link: "",
		timestamp: "5 days ago",
		message:
			"Hello, thanks for setting up the Chess Club, I've been a member for a few weeks now nad I'm already having lots of fun and improving my game.",
		avatar: "../../public/assets/images/avatar-rizky-hasanuddin.webp",
		picture: "",
		isread: "yes",
	},
	{
		username: "Kimberly Smith",
		paragraph: "commented on your picture",
		link: "",
		timestamp: "1week ago",
		message: "",
		avatar: "../../public/assets/images/avatar-kimberly-smith.webp",
		picture: "../../public/assets/images/image-chess.webp",
		isread: "yes",
	},
	{
		username: "Nathan Peterson",
		paragraph: "react to your recent post ",
		link: "5 end-game strategies to increase your wun rate",
		timestamp: "2 weeks ago",
		message: "",
		avatar: "../../public/assets/images/avatar-nathan-peterson.webp",
		picture: "",
		isread: "yes",
	},
	{
		username: "Anna Kim",
		paragraph: "left the group ",
		link: "Chess Club",
		timestamp: "2 weeks ago",
		message: "",
		avatar: "../../public/assets/images/avatar-anna-kim.webp",
		picture: "",
		isread: "yes",
	},
]
